# Generated by Django 5.1.15 on 2026-06-28 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(default='کلینیک زیبایی', max_length=120, verbose_name='نام کلینیک')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('about', models.TextField(blank=True, verbose_name='درباره ما')),
                ('instagram', models.CharField(blank=True, max_length=120, verbose_name='اینستاگرام')),
                ('slot_step_minutes', models.PositiveIntegerField(default=30, help_text='بازه زمانی بین اسلات\u200cهای قابل رزرو.', verbose_name='گام زمانی اسلات\u200cها (دقیقه)')),
                ('max_advance_days', models.PositiveIntegerField(default=30, help_text='مشتری تا چند روز آینده می\u200cتواند نوبت بگیرد.', verbose_name='حداکثر روز رزرو در آینده')),
                ('min_advance_hours', models.PositiveIntegerField(default=2, help_text='رزرو باید حداقل چند ساعت قبل از زمان نوبت انجام شود.', verbose_name='حداقل فاصله رزرو (ساعت)')),
            ],
            options={
                'verbose_name': 'تنظیمات کلینیک',
                'verbose_name_plural': 'تنظیمات کلینیک',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(help_text='نمونه: ۰۹۱۲۱۲۳۴۵۶۷', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود شده')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['mobile'], name='core_custom_mobile_499279_idx'), models.Index(fields=['last_name', 'first_name'], name='core_custom_last_na_26c85e_idx')],
            },
        ),
    ]
