# Generated by Django 5.1.15 on 2026-06-28 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ('-created_at',),
            },
        ),
    ]
