# Generated by Django 5.1.15 on 2026-06-28 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(help_text='یک عنوان کوتاه برای این نمونه؛ مثلاً «جوان\u200cسازی پوست» یا «کاشت ابرو».', max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, help_text='یک یا دو جمله درباره\u200cی این نمونه (اختیاری).', max_length=250, verbose_name='توضیح کوتاه')),
                ('before_image', models.ImageField(help_text='عکس «قبل از درمان» را اینجا آپلود کنید (فرمت JPG یا PNG).', upload_to='before_after/', verbose_name='تصویر قبل')),
                ('after_image', models.ImageField(help_text='عکس «بعد از درمان» را اینجا آپلود کنید (فرمت JPG یا PNG).', upload_to='before_after/', verbose_name='تصویر بعد')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود (مثلاً ۱ اول، ۲ بعد از آن).', verbose_name='اولویت نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگر تیک برداشته شود، این نمونه در سایت نمایش داده نمی\u200cشود.', verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'نمونه قبل و بعد',
                'verbose_name_plural': 'گالری قبل و بعد',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('question', models.CharField(help_text='متن سوالی که کاربران معمولاً می\u200cپرسند.', max_length=255, verbose_name='پرسش')),
                ('answer', models.TextField(help_text='پاسخ کامل و روشن به این پرسش.', verbose_name='پاسخ')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.', verbose_name='اولویت نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگر تیک برداشته شود، این پرسش در صفحه سوالات متداول نمایش داده نمی\u200cشود.', verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'پرسش متداول',
                'verbose_name_plural': 'پرسش\u200cهای متداول',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(help_text='نمونه: ۰۹۱۲۱۲۳۴۵۶۷', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('message', models.TextField(blank=True, help_text='توضیح کوتاه درباره\u200cی نیاز یا سوال کاربر (اختیاری).', verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'تماس گرفته نشده'), ('in_progress', 'در حال پیگیری'), ('done', 'انجام شده')], default='new', max_length=20, verbose_name='وضعیت درخواست')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='website_con_status_b19a9e_idx'), models.Index(fields=['-created_at'], name='website_con_created_be2d2f_idx')],
            },
        ),
    ]
