# Generated by Django 5.1.15 on 2026-06-28 00:33

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('date', django_jalali.db.models.jDateField(unique=True, verbose_name='تاریخ (شمسی)')),
                ('reason', models.CharField(blank=True, max_length=140, verbose_name='علت')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=90, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات',
                'verbose_name_plural': 'دسته\u200cبندی خدمات',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان خدمت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='مدت\u200cزمان (دقیقه)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='appointments.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ('weekday', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_working_hour_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='working_hour_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ (شمسی)')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('done', 'انجام شده'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت کلینیک')),
                ('tracking_code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='کد پیگیری')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.customer', verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ('-date', '-start_time'),
                'indexes': [models.Index(fields=['date'], name='appointment_date_85c852_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('date', 'start_time'), name='unique_active_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start')],
            },
        ),
    ]
