# Generated by Django 5.1.15 on 2026-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, help_text='شناسه تراکنش دریافتی از زرین\u200cپال هنگام شروع پرداخت.', max_length=64, verbose_name='کد Authority درگاه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ref_id',
            field=models.CharField(blank=True, help_text='شماره مرجع تراکنش موفق.', max_length=64, verbose_name='کد رهگیری پرداخت (RefID)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('payment_failed', 'پرداخت ناموفق'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('done', 'انجام شده'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور')], default='waiting_payment', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'payment_failed']), _negated=True), fields=('date', 'start_time'), name='unique_active_slot'),
        ),
    ]
